// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp8Ek466qk3Oyy_mJam2OaX7f18saM0rs',
    appId: '1:132791449664:web:814f0df4dbb05f8dfc87a5',
    messagingSenderId: '132791449664',
    projectId: 'wood-analyser-app',
    authDomain: 'wood-analyser-app.firebaseapp.com',
    storageBucket: 'wood-analyser-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY3YyoTecrgUpRN2SP7qBdgJeN9_OEs9I',
    appId: '1:132791449664:android:4180a376c703b703fc87a5',
    messagingSenderId: '132791449664',
    projectId: 'wood-analyser-app',
    storageBucket: 'wood-analyser-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPDkUk0UGcyzAmdsUpsa1aHGc5jfrok8I',
    appId: '1:132791449664:ios:7315a057f660b401fc87a5',
    messagingSenderId: '132791449664',
    projectId: 'wood-analyser-app',
    storageBucket: 'wood-analyser-app.appspot.com',
    iosClientId: '132791449664-b2jo0aai5oe33e9su8biptrgialbsf9q.apps.googleusercontent.com',
    iosBundleId: 'com.example.woodAnalyzer',
  );
}
